apiVersion: v1
kind: ConfigMap
metadata:
  name: uffizzi-web-service-envs

data:
  ALLOWED_HOSTS: {{ .Values.allowed_hosts | quote }}
  RAILS_PORT: "7000"
  RAILS_SERVE_STATIC_FILES: "true"
  RAILS_THREADS_COUNT: "8"
  RAILS_WORKERS_COUNT: "2"
