apiVersion: v1
kind: ConfigMap
metadata:
  name: uffizzi-web-common-envs
data:
  DATABASE_POOL: "16"
  DATABASE_PORT: {{ .Values.global.postgresql.service.ports.postgresql | quote }}
  DATABASE_HOST: {{ default (print .Release.Name "-postgresql") .Values.db_host | quote }}
  RAILS_ENV: {{ .Values.env | quote }}
  APP_URL: {{ .Values.app_url }}
  CONTROLLER_URL: {{ default (print "http://" .Release.Name "-controller:8080") .Values.controller_url }}
  EMAIL_DELIVERY_ENABLED: {{ .Values.feature_email_delivery | quote }}
  MANAGED_DNS_ZONE_DNS_NAME: {{ .Values.managed_dns_zone_dns_name | quote }}
  UFFIZZI_USER_EMAIL: {{ .Values.uffizzi_user_email }}
  UFFIZZI_USER_PASSWORD: {{ .Values.uffizzi_user_password | quote }}
  UFFIZZI_PROJECT_NAME: {{ .Values.uffizzi_project_name }}
