apiVersion: v1
kind: Secret
metadata:
  name: uffizzi-web-secret-envs
type: Opaque
data:
    DATABASE_USER: {{ .Values.global.postgresql.auth.username | b64enc }}
    DATABASE_PASSWORD: {{ .Values.global.postgresql.auth.password | b64enc }}
    DATABASE_NAME: {{ .Values.global.postgresql.auth.database | b64enc }}
    RAILS_SECRET_KEY_BASE: {{ .Values.rails_secret_key_base | default (printf "%x" (randAscii 64))| b64enc }}
    REDIS_URL: {{ default (print "redis://:" .Values.global.redis.password "@" .Release.Name "-redis-master") .Values.redis_url | b64enc }}
    APP_LOGIN: {{ .Values.basic_auth_login | b64enc }}
    APP_PASSWORD: {{ .Values.basic_auth_password | b64enc }}
    SIDEKIQ_LOGIN: {{ .Values.basic_auth_login | b64enc }}
    SIDEKIQ_PASSWORD: {{ .Values.basic_auth_password | b64enc }}
    CONTROLLER_LOGIN: {{ .Values.global.uffizzi.controller.username | b64enc }}
    CONTROLLER_PASSWORD: {{ .Values.global.uffizzi.controller.password | b64enc }}
    GITHUB_APP_ID: {{ .Values.github_app_id | b64enc }}
    GITHUB_APP_SLUG: {{ .Values.github_app_slug | b64enc }}
    GITHUB_CLIENT_ID: {{ .Values.github_client_id | b64enc }}
    GITHUB_CLIENT_SECRET: {{ .Values.github_client_secret | b64enc }}
    GITHUB_PRIVATE_KEY: {{ .Values.github_private_key | b64enc }}
    GITHUB_WEBHOOK_SECRET: {{ .Values.github_webhook_secret | b64enc }}
