apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-web-ingress
  annotations:
    cert-manager.io/cluster-issuer: {{ print .Release.Name "-" (index (.Values) "uffizzi-controller" "clusterIssuer") }}
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: {{ .Values.webHostname }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-web-service
            port:
              number: 80
  tls:
  - secretName: {{ .Values.webHostname }}
    hosts:
    - {{ .Values.webHostname }}
