rails:
  secret_key_base: <%= ENV['RAILS_SECRET_KEY_BASE'] %>
app:
  ttl_reset_password_token: 900
  host: <%= ENV['APP_URL'] %>
  login:  <%= ENV['APP_LOGIN'] || '' %>
  password:  <%= ENV['APP_PASSWORD'] || '' %>
  managed_dns_zone: <%= ENV['MANAGED_DNS_ZONE_DNS_NAME'] %>
github:
  app_id: <%= ENV['GITHUB_APP_ID'] %>
  app_slug: <%= ENV['GITHUB_APP_SLUG'] %>
  client_id: <%= ENV['GITHUB_CLIENT_ID'] %>
  client_secret: <%= ENV['GITHUB_CLIENT_SECRET'] %>
  private_key: "<%= ENV['GITHUB_PRIVATE_KEY'] %>"
  webhook_secret: <%= ENV['GITHUB_WEBHOOK_SECRET'] %>
docker_hub:
  registry_url: 'https://index.docker.io/v1/'
  public_namespace: 'library'
sidekiq:
  login:  <%= ENV['SIDEKIQ_LOGIN'] || '' %>
  password:  <%= ENV['SIDEKIQ_PASSWORD'] || '' %>
controller:
  url:  <%= ENV['CONTROLLER_URL'] || 'http://controller:8080' %>
  login:  <%= ENV['CONTROLLER_LOGIN'] || '' %>
  password:  <%= ENV['CONTROLLER_PASSWORD'] || '' %>
  connection:
    retires_count: 1
    next_retry_timeout_seconds: 1
    timeout: 7
    open_timeout: 5
  limits:
    cpu: '200m'
  namespace_prefix: 'app-'
  resource_create_retry_time: 15.seconds
  resource_create_retry_count: 60
billing_cycle:
  hours_count: 720
slack:
  invite_url: https://join.slack.com/t/uffizzi/shared_invite/zt-ffr4o3x0-J~0yVT6qgFV~wmGm19Ux9A
allowed_hosts: <%= ENV['ALLOWED_HOSTS']&.split(',') || [] %>
domain: <%= ENV['APP_URL'] %>
sentry:
  dsn: <%= ENV['SENTRY_DSN'] %>
  release: <%= ENV['SENTRY_RELEASE'] %>
  env: <%= Rails.env %>
features:
  email_delivery_enabled: <%= !!ActiveModel::Type::Boolean.new.cast(ENV['EMAIL_DELIVERY_ENABLED']) %>
  stripe_enabled: <%= !!ActiveModel::Type::Boolean.new.cast(ENV['STRIPE_ENABLED']) %>
platform_cluster:
  project_id: <%= ENV['PLATFORM_PROJECT_ID'] %>
google:
  registry_url: 'https://gcr.io/'
github_container_registry:
  registry_url: 'https://ghcr.io/'
compose:
  default_memory: 125
  memory_postfixes: <%= ['b', 'k', 'm', 'g'] %>
  memory_values: <%= [125, 250, 500, 1000, 2000, 4000] %>
  port_min_value: 1
  port_max_value: 65535
  delete_after_postfixes: <%= ['h'] %>
  delete_after_min_value: 1
  delete_after_max_value: 720
  default_tag: latest
  dockerfile_default_path: Dockerfile
  default_branch: 'master'
continuous_preview:
  default_delete_preview_after: 72
deployment:
  subdomain:
    length_limit: 63
