name: Publish `main` branch to Docker Hub as `latest`.
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push Image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: uffizzi/app:latest
      - name: Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v2.4.3
        with:
          # Docker Hub username
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          # Docker Hub password
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          # Docker Hub repository in the format `<namespace>/<name>` Default: `github.repository`
          repository: axisofentropy/example-voting-app-${{ matrix.app }}
          # Docker Hub repository short description Input exceeding 100 characters will be truncated
          # short-description: # optional
          # Path to the repository readme Default: `./README.md`
          # readme-filepath: # optional
